figures<- function(n){

if(n==1)
	{
	out<- subset(all_types, lh=="ssf")
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(Estimate~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	abline(h=vbgf_parms$linf[1],lty=2)
	panLab(expression(L[infinity]))
	axis(1, at=c(1,2,3), labels=FALSE)
	boxplot(Estimate~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	abline(h=vbgf_parms$k[1],lty=2)
	panLab("k")
	boxplot(Estimate~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	abline(h=vbgf_parms$t0[1],lty=2)	
		abline(h=vbgf_parms$t0[1],lty=2)
	mtext(side=2,"Parameter estimate",
		outer=TRUE,line=0)
	}
if(n==2)
	{
	out<- subset(all_types, lh=="ssf")
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(stderr~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	panLab(expression(L[infinity]))	
	
	boxplot(stderr~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	panLab("k")
	boxplot(stderr~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	mtext(side=2,"Estimated standard error",
		outer=TRUE,line=0)
	}
if(n==3)
	{
	out<- subset(all_types, lh=="lls"& bin_n==25)
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(Estimate~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	abline(h=vbgf_parms$linf[2],lty=2)
	panLab(expression(L[infinity]))
	axis(1, at=c(1,2,3), labels=FALSE)
	boxplot(Estimate~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	abline(h=vbgf_parms$k[2],lty=2)
	panLab("k")
	boxplot(Estimate~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	abline(h=vbgf_parms$t0[2],lty=2)	
	mtext(side=2,"Parameter estimate",
		outer=TRUE,line=0)
	}
if(n==4)
	{
	out<- subset(all_types, lh=="lls"& bin_n==25)
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(stderr~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	panLab(expression(L[infinity]))	
	boxplot(stderr~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	panLab("k")
	boxplot(stderr~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	mtext(side=2,"Estimated standard error",
		outer=TRUE,line=0)
	}
if(n==5)
	{
	out<- subset(all_types, lh=="lls"& bin_n==10)
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(Estimate~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	abline(h=vbgf_parms$linf[2],lty=2)
	panLab(expression(L[infinity]))
	axis(1, at=c(1,2,3), labels=FALSE)
	boxplot(Estimate~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	abline(h=vbgf_parms$k[2],lty=2)
	panLab("k")
	boxplot(Estimate~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	abline(h=vbgf_parms$t0[2],lty=2)	
	mtext(side=2,"Parameter estimate",
		outer=TRUE,line=0)
	}
if(n==6)
	{
	out<- subset(all_types, lh=="lls"& bin_n==10)
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(stderr~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	panLab(expression(L[infinity]))	
	boxplot(stderr~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	panLab("k")
	boxplot(stderr~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	mtext(side=2,"Estimated standard error",
		outer=TRUE,line=0)
	}
if(n==7)
	{
	out<- subset(all_types, lh=="lls"& bin_int==10 & bin_n==10)
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(Estimate~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	abline(h=vbgf_parms$linf[2],lty=2)
	panLab(expression(L[infinity]))
	axis(1, at=c(1,2,3), labels=FALSE)
	boxplot(Estimate~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	abline(h=vbgf_parms$k[2],lty=2)
	panLab("k")
	boxplot(Estimate~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	abline(h=vbgf_parms$t0[2],lty=2)	
	mtext(side=2,"Parameter estimate",
		outer=TRUE,line=0)
		hist(out$prop_bin_fill)

	out<- subset(all_types, lh=="lls"& bin_int==10 & bin_n==25)		
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(Estimate~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	abline(h=vbgf_parms$linf[2],lty=2)
	panLab(expression(L[infinity]))
	axis(1, at=c(1,2,3), labels=FALSE)
	boxplot(Estimate~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	abline(h=vbgf_parms$k[2],lty=2)
	panLab("k")
	boxplot(Estimate~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	abline(h=vbgf_parms$t0[2],lty=2)	
	mtext(side=2,"Parameter estimate",
		outer=TRUE,line=0)	
		hist(out$prop_bin_fill)		
	}
	}
if(n==8)
	{
	out<- subset(all_types, lh=="lls"& bin_int==25)
	par(mfrow=c(3,1),mar=c(1,4,0,1),oma=c(2,2,1,1))
	boxplot(Estimate~type,out, subset=parm=="Linf",xaxt='n',las=1,ylab="")
	abline(h=vbgf_parms$linf[2],lty=2)
	panLab(expression(L[infinity]))
	axis(1, at=c(1,2,3), labels=FALSE)
	boxplot(Estimate~type,out, subset=parm=="k",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=FALSE)
	abline(h=vbgf_parms$k[2],lty=2)
	panLab("k")
	boxplot(Estimate~type,out, subset=parm=="t0",xaxt='n',las=1,ylab="")
	axis(1, at=c(1,2,3), labels=c("Binned", "Reweighted","Random sample"))
	panLab(expression(t[0]))
	abline(h=vbgf_parms$t0[2],lty=2)	
	mtext(side=2,"Parameter estimate",
		outer=TRUE,line=0)
	}
}